//  let basUrl='http://172.16.56.77:10100/api';
let basUrl='https://customerapp.ime.co.ir:10100/api';

export const AppUrl = {
  'categories': basUrl+'/ComponentModel',
  'wishlist': '/api/wishlist',
  'shoppingCart': '/api/shoppingCart',
  'states': '/api/states',
  'taxes': '/api/taxes',
  'usersInfo': '/api/usersInfo',
  'customers':basUrl+'/common/customer',
  'credit':basUrl+'/credit',
  'broker':basUrl+'/common/broker',
   'martials':basUrl+'/common/Maritals', 
   'associations':basUrl+'/common/Associations',
   'partnership':basUrl+'/common/Partnerships',
   'currencies':basUrl+'/common/Currencies', 
  'categoryCredit':basUrl+'/credit-category',
  'bank':basUrl+'/common/banks',
  'bankAccountTypes':basUrl+'/common/bankAccountTypes',
  'Cities': basUrl+'/common/Cities',
  'Countries': basUrl+'/common/Countries',
  'Educations': basUrl+'/common/Educationdegrees',
  'States': basUrl+'/common/States',
  'Genders': basUrl+'/common/Genders',
  'login':basUrl+'/account',
   'customerType':basUrl+'/common/customerTypes',
   'addressType':basUrl+'/common/addressTypes',
   'brokerRequests':basUrl+'/broker/Requests/brief', 
   'identityType':basUrl+'/common/identityTypes',
    'inquiryTaxpaer':basUrl+'/Inquiries/TaxPayerInfo/meta/',
    'inquirylegalInfo':basUrl+'/inquiries/legalPersoninfo/meta/',
    'inquiryDepository':basUrl+'/inquiries/depositoryinfo/meta/',
    'inquiryfidaLegalPerson':basUrl+'/Inquiries/ForeignersInfo/LegalPerson/meta/',
    'inquiryfidanaturalPerson':basUrl+'/Inquiries/ForeignersInfo/NaturalPerson/meta/',
    'verifyCellInfoIndividualPerson':basUrl+'/Inquiries/VerifyCellInfo/IndividualPerson/meta/',
    'verifyCellInfoLegalPerson':basUrl+'/Inquiries/VerifyCellInfo/LegalPerson/meta/',
     'legalTypes':basUrl+'/common/FirmTypes',
     'directorateAuthoritiesTypes':basUrl+'/common/DirectorateAuthorities',
     'freeZones':basUrl+'/common/FreeZones',
     'measurementUnits':basUrl+'/common/MeasurementUnits',
     'positions':basUrl+'/common/Positions',
     'zonesOfActivity':basUrl+'/common/ZoneOfActivities',
     'chekIsExistExternalId':basUrl+'/broker/Customers/externalId/exists/',
     'chekIsExistExternalIdWithBreifInformation':basUrl+'/broker/Requests/Assign/check',
    'inquiryDepositoryByNationalID':basUrl+'/Inquiries/Warehouseinfo/meta/',
    'behinyabinfo':basUrl+'/Inquiries/behinyabinfo/meta/',
    'customerInfo':basUrl+'/Inquiries/tsetmc/customerinfo/meta/',
    'incomeTaxReturn':basUrl+'/Inquiries/IncomeTaxReturn/meta/',
    'saveLegalInteriorNewRequest':basUrl+'/broker/Requests/Add/Legal/Interior',
    'savePublicNewRequest':basUrl+'/broker/Requests/Add/Public',
    'saveLegalInteriorEditOfNewRequest':basUrl+'/broker/Requests/Add/Legal/Interior/',
    'savePublicEditOfNewRequest':basUrl+'/broker/Requests/Add/Public/',
    'saveIndividualInteriorNewRequest':basUrl+'/broker/Requests/Add/Individual/Interior',
    'saveIndividualInteriorEditOfNewRequest':basUrl+'/broker/Requests/Add/Individual/Interior/',
    'seriesLetters':basUrl+'/common/PersianLetters',
    'sendAddDraftIndividualInteriorToServer':basUrl+'/broker/Requests/Add/Individual/Interior/',
    'deletePublicRequest':basUrl+'/broker/requests/Add/public/',
    'sendAddDraftLegalInteriorToServer':basUrl+'/broker/Requests/Add/Legal/Interior/',
    'sendAddDraftPublicToServer':basUrl+'/broker/requests/Add/public/',
    'allCustomersOfBroker':basUrl+'/broker/Customers/brief/',
    'keyOfPublishSignatureAuthority':basUrl+'/broker/Requests/publishSignatureAuthority/',
    'keyOfIndividualInteriorForExportPdf':basUrl+'/broker/Requests/publish/',
    'getPdfOfRequestByKey':basUrl+'/Reports/CustomerRequestForm/ExportPdf',
    'getPdfOfIndividualAuthoritySignatureForm':basUrl+'/Reports/IndividualAuthoritySignatureForm/ExportPdf',
    'SignedRightHolders':basUrl+'/Reports/LegalAuthoritySignatureForm/ExportPdf',
    'getIndividualInteriorBrokerRequest':basUrl+'/broker/Requests/Add/Individual/Interior/',
    'getLegalInteriorBrokerRequest':basUrl+'/broker/Requests/Add/Legal/Interior/',
    'getPublicBrokerRequest':basUrl+'/broker/requests/add/public/',
    'licenseInfoByNationalCode':basUrl+'/Inquiries/licenseinfo/bynationalCode/meta/',
    'licenseInfoByNationalId':basUrl+'/Inquiries/licenseinfo/bynationalid/meta/',
    'licenseInfoByBusinessId':basUrl+'/Inquiries/licenseinfo/bybusinessId/meta/',
    'inquirylegalInteriorRequestInfo':basUrl+'/injections/Legal/Interior/',
    'inquirylegalExteriorRequestInfo':basUrl+'/injections/Legal/Exterior/',
    'inquiryIndividualInteriorRequestInfo':basUrl+'/injections/Individual/Interior/',
    'inquiryIndividualExteriorRequestInfo':basUrl+'/injections/Individual/Exterior/',
    'inquiryPublicRequestInfo':basUrl+'/injections/Public/Interior/',
    'specialZones':basUrl+'/common/SpecialZones',
    'sendDraftAssignRequestToServer':basUrl+'/broker/Requests/Assign',
    'sendAssignDraftRequestToServer':basUrl+'/broker/Requests/Assign/',
    'sendDraftRemoveRequestToServer':basUrl+'/broker/Requests/Remove',
    'sendRemoveDraftRequestToServer':basUrl+'/broker/Requests/Remove/'
};

// 'categories': 'http://172.16.56.77:1010/ComponentModel',
